# Build customization
before:
  hooks:
    - go mod download

builds:
  - main: .
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    binary: k8spin
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 5
      - 6
      - 7

archives:
  - id: k8spin
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: arm
      arm64: arm64
      darwin: macOS
      linux: linux
      windows: windows
    files:
    - README.md
    - LICENSE