# Build customization
before:
  hooks:
    - go mod download
builds:
  - main: .
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    binary: k8spin
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 5
      - 6
      - 7
archive:
  format: binary